// @generated by scripts/build-module-manifest.mjs — DO NOT EDIT BY HAND.
// Re-run `node scripts/build-module-manifest.mjs` after adding/removing/renaming
// a manifests/*.ts file or changing its `order`. The committed copy is byte-pinned
// by registry.test.ts's staleness guard.
//
// SCANNED manifests/*.ts → sorted by each manifest's `order` field. This is the
// SINGLE source of the registered module set + order; no import.meta.glob (a
// static import list resolves under bare tsx/Node, not just the Vite graph).
import type { ModuleManifest } from '../types'
import { coreManifest } from './core'
import { governanceManifest } from './governance'

/** All registered module manifests, in `order` (registration) sequence. */
export const MODULE_MANIFESTS: ModuleManifest[] = [
  coreManifest,
  governanceManifest,
]
