// @generated by scripts/build-module-server-init.mjs — DO NOT EDIT BY HAND.
// Re-run `node scripts/build-module-server-init.mjs` after adding/removing/renaming
// a module's register.server.ts. The committed copy is byte-pinned by
// server-init.generated.test.ts's staleness guard.
//
// SCANNED src/lib/server for register.server.ts files. Importing this barrel
// once (from hooks.server.ts) runs every module's self-registration into
// runtime-registry.ts (boot hooks + tenant-evict hooks + provisioning
// subsystem factories). No import.meta.glob (a static import list resolves
// under bare tsx/Node, not just the Vite graph).

